// Code generated by "stringer -type=Subsystem -output=subsystem.stringer.go"; DO NOT EDIT.

package promgrpc

import "strconv"

const _Subsystem_name = "ServerClient"

var _Subsystem_index = [...]uint8{0, 6, 12}

func (i Subsystem) String() string {
	i -= 1
	if i < 0 || i >= Subsystem(len(_Subsystem_index)-1) {
		return "Subsystem(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Subsystem_name[_Subsystem_index[i]:_Subsystem_index[i+1]]
}
